<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bonificacion_automatica".
 *
 * @property integer $id
 * @property string $descripcion
 * @property string $valor
 * @property integer $cantidad_hemanos
 * @property boolean $activa
 * @property string $aliasModel
 */
abstract class BonificacionAutomatica extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bonificacion_automatica';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descripcion', 'valor', 'cantidad_hemanos'], 'required'],
            [['valor'], 'number'],
            [['cantidad_hemanos'], 'integer'],
            [['activa'], 'boolean'],
            [['descripcion'], 'string', 'max' => 255],
           
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descripcion' => 'Descripcion',
            'valor' => 'Valor',
            'cantidad_hemanos' => 'Cantidad Hemanos',
            'activa' => 'Activa',
        ];
    }




}
