<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bonificaciones".
 *
 * @property integer $id
 * @property string $descripcion
 * @property string $valor
 * @property boolean $activa
 * @property boolean $automatica
 * @property integer $cantidad_hermanos
 *
 * @property \app\models\BonificacionServicioAlumno[] $bonificacionServicioAlumnos
 * @property string $aliasModel
 */
abstract class Bonificaciones extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bonificaciones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descripcion', 'valor', 'cantidad_hermanos'], 'required'],
            [['valor'], 'number'],
            [['activa', 'automatica'], 'boolean'],
            [['cantidad_hermanos'], 'integer'],
            [['descripcion'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descripcion' => 'Descripcion',
            'valor' => 'Valor',
            'activa' => 'Activa',
            'automatica' => 'Automatica',
            'cantidad_hermanos' => 'Cantidad Hermanos',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacionServicioAlumnos()
    {
        return $this->hasMany(\app\models\BonificacionServicioAlumno::className(), ['id_bonificacion' => 'id']);
    }




}
