<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "division_escolar".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $id_establecimiento
 * @property integer $id_divisionegreso
 * @property string $iniciales
 *
 * @property \app\models\Alumno[] $alumnos
 * @property \app\models\Establecimiento $establecimiento
 * @property \app\models\DivisionEscolar $divisionegreso
 * @property \app\models\DivisionEscolar[] $divisionEscolars
 * @property \app\models\ServicioDivisionescolar[] $servicioDivisionescolars
 * @property string $aliasModel
 */
abstract class DivisionEscolar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'division_escolar';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'id_establecimiento'], 'required'],
            [['id_establecimiento', 'id_divisionegreso'], 'integer'],
            [['nombre'], 'string', 'max' => 255],
            [['iniciales'], 'string', 'max' => 100],
            [['id_establecimiento'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Establecimiento::className(), 'targetAttribute' => ['id_establecimiento' => 'id']],
            [['id_divisionegreso'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\DivisionEscolar::className(), 'targetAttribute' => ['id_divisionegreso' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'id_establecimiento' => 'Id Establecimiento',
            'id_divisionegreso' => 'Id Divisionegreso',
            'iniciales' => 'Iniciales',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumnos()
    {
        return $this->hasMany(\app\models\Alumno::className(), ['id_divisionescolar' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstablecimiento()
    {
        return $this->hasOne(\app\models\Establecimiento::className(), ['id' => 'id_establecimiento']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionegreso()
    {
        return $this->hasOne(\app\models\DivisionEscolar::className(), ['id' => 'id_divisionegreso']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionEscolars()
    {
        return $this->hasMany(\app\models\DivisionEscolar::className(), ['id_divisionegreso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioDivisionescolars()
    {
        return $this->hasMany(\app\models\ServicioDivisionescolar::className(), ['id_divisionescolar' => 'id']);
    }




}
