<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "historia_egresos_alumno".
 *
 * @property integer $id
 * @property integer $id_alumno
 * @property integer $id_division_actual
 * @property integer $id_division_egreso
 * @property string $fecha
 *
 * @property \app\models\Alumno $alumno
 * @property \app\models\DivisionEscolar $divisionActual
 * @property \app\models\DivisionEscolar $divisionEgreso
 * @property string $aliasModel
 */
abstract class HistoriaEgresosAlumno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'historia_egresos_alumno';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_alumno', 'id_division_actual', 'fecha'], 'required'],
            [['id_alumno', 'id_division_actual', 'id_division_egreso'], 'integer'],
            [['fecha'], 'safe'],
            [['id_alumno'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Alumno::className(), 'targetAttribute' => ['id_alumno' => 'id']],
            [['id_division_actual'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\DivisionEscolar::className(), 'targetAttribute' => ['id_division_actual' => 'id']],
            [['id_division_egreso'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\DivisionEscolar::className(), 'targetAttribute' => ['id_division_egreso' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_alumno' => 'Id Alumno',
            'id_division_actual' => 'Id Division Actual',
            'id_division_egreso' => 'Id Division Egreso',
            'fecha' => 'Fecha',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumno()
    {
        return $this->hasOne(\app\models\Alumno::className(), ['id' => 'id_alumno']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionActual()
    {
        return $this->hasOne(\app\models\DivisionEscolar::className(), ['id' => 'id_division_actual']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionEgreso()
    {
        return $this->hasOne(\app\models\DivisionEscolar::className(), ['id' => 'id_division_egreso']);
    }




}
