<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "log_factura".
 *
 * @property integer $id
 * @property string $error
 * @property string $fecha_prueba
 * @property integer $id_factura
 * @property string $aliasModel
 */
abstract class LogFactura extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'log_factura';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['error', 'fecha_prueba', 'id_factura'], 'required'],
            [['fecha_prueba'], 'safe'],
            [['id_factura'], 'integer'],
            [['error'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'error' => 'Error',
            'fecha_prueba' => 'Fecha Prueba',
            'id_factura' => 'Id Factura',
        ];
    }




}
