<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicio_debito_automatico".
 *
 * @property integer $id
 * @property integer $id_debitoautomatico
 * @property integer $id_servicio
 * @property string $tiposervicio
 * @property string $resultado_procesamiento
 * @property string $linea
 * @property integer $id_familia
 * @property double $importe
 *
 * @property \app\models\DebitoAutomatico $debitoautomatico
 * @property \app\models\GrupoFamiliar $familia
 * @property string $aliasModel
 */
abstract class ServicioDebitoAutomatico extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicio_debito_automatico';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_debitoautomatico', 'id_servicio', 'id_familia', 'importe'], 'required'],
            [['id_debitoautomatico', 'id_servicio', 'id_familia'], 'integer'],
            [['importe'], 'number'],
            [['tiposervicio', 'resultado_procesamiento', 'linea'], 'string', 'max' => 255],
            [['id_debitoautomatico'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\DebitoAutomatico::className(), 'targetAttribute' => ['id_debitoautomatico' => 'id']],
            [['id_familia'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\GrupoFamiliar::className(), 'targetAttribute' => ['id_familia' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_debitoautomatico' => 'Id Debitoautomatico',
            'id_servicio' => 'Id Servicio',
            'tiposervicio' => 'Tiposervicio',
            'resultado_procesamiento' => 'Resultado Procesamiento',
            'linea' => 'Linea',
            'id_familia' => 'Id Familia',
            'importe' => 'Importe',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebitoautomatico()
    {
        return $this->hasOne(\app\models\DebitoAutomatico::className(), ['id' => 'id_debitoautomatico']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFamilia()
    {
        return $this->hasOne(\app\models\GrupoFamiliar::className(), ['id' => 'id_familia']);
    }




}
