<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicio_alumno".
 *
 * @property integer $id
 * @property integer $id_servicio
 * @property integer $id_alumno
 * @property string $fecha_otorgamiento
 * @property string $fecha_cancelamiento
 * @property string $importe_servicio
 * @property string $importe_descuento
 * @property string $importe_abonado
 * @property integer $id_estado
 *
 * @property \app\models\BonificacionServicioAlumno[] $bonificacionServicioAlumnos
 * @property \app\models\Alumno $alumno
 * @property \app\models\EstadoServicio $estado
 * @property \app\models\ServicioDivisionescolar $servicio
 * @property string $aliasModel
 */
abstract class ServicioAlumno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicio_alumno';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_servicio', 'id_alumno', 'fecha_otorgamiento', 'importe_servicio', 'importe_descuento', 'importe_abonado', 'id_estado'], 'required'],
            [['id_servicio', 'id_alumno', 'id_estado'], 'integer'],
            [['fecha_otorgamiento', 'fecha_cancelamiento'], 'safe'],
            [['importe_servicio', 'importe_descuento', 'importe_abonado'], 'number'],
            [['id_alumno'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Alumno::className(), 'targetAttribute' => ['id_alumno' => 'id']],
            [['id_estado'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EstadoServicio::className(), 'targetAttribute' => ['id_estado' => 'id']],
            [['id_servicio'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServicioOfrecido::className(), 'targetAttribute' => ['id_servicio' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_servicio' => 'Id Servicio',
            'id_alumno' => 'Id Alumno',
            'fecha_otorgamiento' => 'Fecha Otorgamiento',
            'fecha_cancelamiento' => 'Fecha Cancelamiento',
            'importe_servicio' => 'Importe Servicio',
            'importe_descuento' => 'Importe Descuento',
            'importe_abonado' => 'Importe Abonado',
            'id_estado' => 'Id Estado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacionServicioAlumnos()
    {
        return $this->hasMany(\app\models\BonificacionServicioAlumno::className(), ['id_servicioalumno' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumno()
    {
        return $this->hasOne(\app\models\Alumno::className(), ['id' => 'id_alumno']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\app\models\EstadoServicio::className(), ['id' => 'id_estado']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicio()
    {
        return $this->hasOne(\app\models\ServicioOfrecido::className(), ['id' => 'id_servicio']);
    }




}
