<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicios_tiket".
 *
 * @property integer $id
 * @property integer $id_tiket
 * @property integer $id_servicio
 * @property integer $tiposervicio
 * @property string $monto_abonado
 *
 * @property \app\models\Tiket $tiket
 * @property string $aliasModel
 */
abstract class ServiciosTiket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicios_tiket';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_tiket', 'id_servicio', 'tiposervicio', 'monto_abonado'], 'required'],
            [['id_tiket', 'id_servicio', 'tiposervicio'], 'integer'],
            [['monto_abonado'], 'number'],
            [['id_tiket'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tiket::className(), 'targetAttribute' => ['id_tiket' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_tiket' => 'Id Tiket',
            'id_servicio' => 'Id Servicio',
            'tiposervicio' => 'Tiposervicio',
            'monto_abonado' => 'Monto Abonado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTiket()
    {
        return $this->hasOne(\app\models\Tiket::className(), ['id' => 'id_tiket']);
    }




}
