<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicio_ofrecido".
 *
 * @property integer $id
 * @property integer $id_categoriaservicio
 * @property string $nombre
 * @property string $descripcion
 * @property string $importe
 * @property string $importe_hijoprofesor
 * @property string $fecha_inicio
 * @property string $fecha_fin
 * @property string $fecha_vencimiento
 * @property boolean $devengamiento_automatico
 * @property boolean $activo
 *
 * @property \app\models\ServicioAlumno[] $servicioAlumnos
 * @property \app\models\ServicioDivisionescolar[] $servicioDivisionescolars
 * @property \app\models\CategoriaServicioOfrecido $categoriaservicio
 * @property string $aliasModel
 */
abstract class ServicioOfrecido extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicio_ofrecido';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_categoriaservicio', 'nombre', 'importe', 'importe_hijoprofesor'], 'required'],
            [['id_categoriaservicio'], 'integer'],
            [['importe', 'importe_hijoprofesor'], 'number'],
            [['fecha_inicio', 'fecha_fin', 'fecha_vencimiento'], 'safe'],
            [['devengamiento_automatico', 'activo'], 'boolean'],
            [['nombre'], 'string', 'max' => 100],
            [['descripcion'], 'string', 'max' => 255],
            [['id_categoriaservicio'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoriaServicioOfrecido::className(), 'targetAttribute' => ['id_categoriaservicio' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_categoriaservicio' => 'Id Categoriaservicio',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'importe' => 'Importe',
            'importe_hijoprofesor' => 'Importe Hijoprofesor',
            'fecha_inicio' => 'Fecha Inicio',
            'fecha_fin' => 'Fecha Fin',
            'fecha_vencimiento' => 'Fecha Vencimiento',
            'devengamiento_automatico' => 'Devengamiento Automatico',
            'activo' => 'Activo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioAlumnos()
    {
        return $this->hasMany(\app\models\ServicioAlumno::className(), ['id_servicio' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioDivisionescolars()
    {
        return $this->hasMany(\app\models\ServicioDivisionescolar::className(), ['id_servicio' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoriaservicio()
    {
        return $this->hasOne(\app\models\CategoriaServicioOfrecido::className(), ['id' => 'id_categoriaservicio']);
    }




}
