<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicio_divisionescolar".
 *
 * @property integer $id
 * @property integer $id_servicio
 * @property integer $id_divisionescolar
 *
 * @property \app\models\ServicioAlumno[] $servicioAlumnos
 * @property \app\models\DivisionEscolar $divisionescolar
 * @property \app\models\ServicioOfrecido $servicio
 * @property string $aliasModel
 */
abstract class ServicioDivisionescolar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicio_divisionescolar';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_servicio', 'id_divisionescolar'], 'required'],
            [['id_servicio', 'id_divisionescolar'], 'integer'],
            [['id_divisionescolar'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\DivisionEscolar::className(), 'targetAttribute' => ['id_divisionescolar' => 'id']],
            [['id_servicio'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServicioOfrecido::className(), 'targetAttribute' => ['id_servicio' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_servicio' => 'Id Servicio',
            'id_divisionescolar' => 'Id Divisionescolar',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioAlumnos()
    {
        return $this->hasMany(\app\models\ServicioAlumno::className(), ['id_servicio' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionescolar()
    {
        return $this->hasOne(\app\models\DivisionEscolar::className(), ['id' => 'id_divisionescolar']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicio()
    {
        return $this->hasOne(\app\models\ServicioOfrecido::className(), ['id' => 'id_servicio']);
    }




}
