<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tiket".
 *
 * @property integer $id
 * @property string $nro_tiket
 * @property string $fecha_tiket
 * @property integer $id_tipopago
 * @property string $importe
 * @property string $fecha_pago
 * @property string $detalles
 * @property integer $id_cliente
 * @property integer $id_cuentapagadora
 * @property boolean $con_servicios
 * @property integer $id_factura
 *
 * @property \app\models\ServiciosTiket[] $serviciosTikets
 * @property \app\models\Cuentas $cuentapagadora
 * @property \app\models\Factura $factura
 * @property \app\models\FormaPago $tipopago
 * @property string $aliasModel
 */
abstract class Tiket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tiket';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_tiket', 'id_tipopago', 'importe', 'fecha_pago', 'id_cuentapagadora'], 'required'],
            [['fecha_tiket', 'fecha_pago'], 'safe'],
            [['id_tipopago', 'id_cliente', 'id_cuentapagadora', 'id_factura'], 'integer'],
            [['importe'], 'number'],
            [['con_servicios'], 'boolean'],
            [['nro_tiket'], 'string', 'max' => 50],
            [['detalles'], 'string', 'max' => 255],
            [['id_cuentapagadora'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cuentas::className(), 'targetAttribute' => ['id_cuentapagadora' => 'id']],
            [['id_factura'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Factura::className(), 'targetAttribute' => ['id_factura' => 'id']],
            [['id_tipopago'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\FormaPago::className(), 'targetAttribute' => ['id_tipopago' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nro_tiket' => 'Nro Tiket',
            'fecha_tiket' => 'Fecha Tiket',
            'id_tipopago' => 'Id Tipopago',
            'importe' => 'Importe',
            'fecha_pago' => 'Fecha Pago',
            'detalles' => 'Detalles',
            'id_cliente' => 'Id Cliente',
            'id_cuentapagadora' => 'Id Cuentapagadora',
            'con_servicios' => 'Con Servicios',
            'id_factura' => 'Id Factura',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiciosTikets()
    {
        return $this->hasMany(\app\models\ServiciosTiket::className(), ['id_tiket' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuentapagadora()
    {
        return $this->hasOne(\app\models\Cuentas::className(), ['id' => 'id_cuentapagadora']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactura()
    {
        return $this->hasOne(\app\models\Factura::className(), ['id' => 'id_factura']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipopago()
    {
        return $this->hasOne(\app\models\FormaPago::className(), ['id' => 'id_tipopago']);
    }




}
